### ISSUE TITLE
Add `Vue Transition CSS` snippets

### ISSUE THREAD

**Issue by ExEr7um** [ExEr7um/vue3-vscode-snippets#30]
Add snippets for creating CSS transitions and transition groups. For example:
```css
.v-enter-active,
.v-leave-active {
  transition: opacity 0.5s ease;
}

.v-enter-from,
.v-leave-to {
  opacity: 0;
}
```
